// 7.react/05day/react-router/src-demo/pages/Home/index.jsx
import React, { Component } from 'react';
import {
  BrowserRouter as Router,
  Switch,
  Route,
  Redirect,
  NavLink,
} from 'react-router-dom';
import Message from './components/Message';
import News from './components/News';

export default class Home extends Component {
  render() {
    return (
      <Router className="panel">
        <div className="panel-body">
          <div>
            <h2>Home组件内容</h2>
            <div>
              <ul className="nav nav-tabs">
                <li>
                  <NavLink to="/home/news">News</NavLink>
                </li>
                <li>
                  <NavLink
                    to="/home/message"
                    className="myActive"
                    aria-current="page">
                    Message
                  </NavLink>
                </li>
              </ul>
              <div className="col-xs-6">
                <Switch>
                  <Route path="/home/news" component={News} />
                  <Route path="/home/message" component={Message} />
                  <Redirect to="/home/message" />
                </Switch>
              </div>
            </div>
          </div>
        </div>
      </Router>
    );
  }
}

// 8.vue/03/vue_test/src/views/Home/index.vue
<template>
  <div class="panel">
    <div class="panel-body">
      <div>
        <h2>Home组件内容</h2>
        <div>
          <ul class="nav nav-tabs">
            <li>
              <router-link to="/home/news" active-class="active">News</router-link>
            </li>
            <li>
              <router-link to="/home/message" active-class="active">Message</router-link>
            </li>
          </ul>
          <router-view />
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "Home",
};
</script>

<style scoped>
/* scoped:  表示样式仅能在当前组件中使用 */
.active {
  background-color: #002fa7 !important;
  color: #fff !important;
}
</style>
