// 8.vue/03/vue_common/src/views/CommentList/CommentItem/index.vue
<template>
  <li class="list-group-item">
    <div class="handle">
      <a href="javascript:;" @click="del(comment.id)">删除</a>
    </div>
    <p class="user">
      <span>{{comment.name}}</span>
      <span>说:</span>
    </p>
    <p class="centence">{{comment.content}}</p>
  </li>
</template>

<script>
export default {
  name: 'CommentItem',
  props: {
    comment: Object,
  },
  methods: {
    del(id) {
      if (!confirm(`确认删除${this.comment.name}的评论吗?`)) return;
      this.$bus.$emit('delComment', id);
    },
  },
};
</script>

<style>
</style>

// 7.react/hello-react/src/pages/CommentList/components/CommentItem/index.jsx
import { Component } from 'react';
import PropTypes from 'prop-types';
export default class CommentItem extends Component {
  static propTypes = {
    comment: PropTypes.object.isRequired,
  };
  /* 点击按钮调用App组件删除的方法 */
  handleDeleteClick = () => {
    this.props.handleDeleteComment(this.props.comment.id);
  };
  render() {
    const { username, content } = this.props.comment;
    return (
      <li className="list-group-item">
        <div className="handle">
          <button onClick={this.handleDeleteClick}>删除</button>
        </div>
        <p className="user">
          <span>{username}</span>
          <span>说:</span>
        </p>
        <p className="centence">{content}</p>
      </li>
    );
  }
}
